packages:
  - Frontend/apps/*
  - Frontend/libs/*

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

overrides:
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  tar@=7.5.1: '>=7.5.2'
